Added get, first, last methods.
Sparhawk96/Owls-Project_SingleLinked-List pull request #26
Opened 2020-12-03 02:20 UTC by SMBSU

Added the get(int index), first(), and last() methods.

2020-12-03 02:22 UTC, Sparhawk96 requested changes
Add exceptions these methods throw. Everything else looks good.

2020-12-03 02:58 UTC, Sparhawk96 approved these changes

2020-12-03 04:35 UTC, droycho approved these changes

2020-12-04 01:03 UTC, EmmaLytle approved these changes

2020-12-04 01:25 UTC, merged